Align parser and ast with new grammar
Yakokse/PEARL pull request #1
Opened 2024-11-19 13:05 UTC by jens270996

Extended AST with new grammar supporting procedures.

Then moved on to "fixing" all the errors that occurred as a result of this change.
This was done by either
 - Fixing error, in cases where the fix was trivial
 - Commenting out function/case and substituting with undefined in non-trivial cases.

2024-11-19 13:07 UTC, jens270996 commented on src/PE/Preprocessing/Division.hs
> +  undefined -- TODO: fix
```suggestion
   undefined --TODO: fix when adding PE support for processes
```

2024-11-19 13:08 UTC, jens270996 commented on src/PE/Preprocessing/Impl/Annotate.hs
> +annotateFrom = undefined -- TODO: fix
```suggestion
annotateFrom  = undefined --TODO: fix when adding PE support for processes
```

2024-11-19 13:09 UTC, jens270996 commented on src/PE/Preprocessing/Impl/Uniform.hs
> +  undefined -- TODO: fix
```suggestion
   undefined --TODO: fix when adding PE support for processes
```

2024-11-19 13:09 UTC, jens270996 commented on src/PE/Preprocessing/Impl/Uniform.hs
> +checkProg p = undefined -- TODO: fix
```suggestion
checkProg p  = undefined --TODO: fix when adding PE support for processes
```

2024-11-19 13:10 UTC, jens270996 commented on src/Parsing/Impl/Program.hs
> +pProcess = undefined
```suggestion
pProcess  = undefined --TODO: fix when adding parsing for processes
```

2024-11-19 13:11 UTC, jens270996 commented on src/RL/AST.hs
> +    appFrom (Entry p s) = Entry p (g s)
```suggestion
    appFrom (Entry p s) = Entry p (g s)  --TODO: is correct?

2024-11-19 13:11 UTC, jens270996 commented on src/RL/AST.hs
> +    appJump (Exit p s) = Exit p (g s)
```suggestion
    appJump (Exit p s) = Exit p (g s) -- TODO: is correct?
```

2024-11-19 13:11 UTC, jens270996 commented on src/RL/AST.hs
> +mapFrom _ (Entry p s) = Entry p s
```suggestion
mapFrom _ (Entry p s) = Entry p s --TODO: is correct?
```

2024-11-19 13:12 UTC, jens270996 commented on src/RL/AST.hs
> +mapJump _ (Exit p s) = Exit p s
```suggestion
mapJump _ (Exit p s) = Exit p s --TODO: is correct?
```

2024-11-19 16:55 UTC, Yakokse requested changes
Lige et par ting som nævnt på Discord og her.

2024-11-19 16:55 UTC, Yakokse commented on src/RL/AST.hs
> +data Process label store = Process
Process -> Procedure (og alle relaterede steder)
Føler det er en god ide lige at få det rigtige navn på plads før der bliver bygget alt for meget.

2024-11-19 16:55 UTC, Yakokse commented on src/RL/AST.hs
> +    appFrom (Entry p s) = Entry p (g s)  --TODO: is correct?
Ser rigtigt ud! (samme andre steder)

2024-11-19 16:55 UTC, Yakokse commented on src/Utils/PrettyPrint.hs
> +prettyFrom _ (Entry p ()) = ["entry( " ++ prettyPat p ++ ")"]
Nu er vi ikke helt færdig med grammatikken, men ideelt for mig vil det være:
`"entry " ++ prettyPat p`
Samme med exit

2024-11-22 19:33 UTC, Yakokse commented on src/Inversion/Impl/Inverter.hs
> +invertFrom (Entry p s)          = Exit p s -- TODO: correct?
Correct👍

2024-11-22 19:34 UTC, Yakokse commented on src/Inversion/Impl/Inverter.hs
> +invertJump (Exit p s)           = Entry p s --TODO: correct?
Correct👍

2024-11-25 10:21 UTC, jens270996 commented on src/Inversion/Impl/Inverter.hs
> +invertFrom (Entry p s)          = Exit p s -- TODO: correct?
```suggestion
invertFrom (Entry p s)          = Exit p s
```

2024-11-25 19:53 UTC, Yakokse approved these changes
LGTM! :)

2024-11-25 20:35 UTC, merged